version: "3.8"

services:
  app:
    image: comment-bot:v1.0.0
    container_name: comment-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./twitter-cookies.json:/app/twitter-cookies.json:ro
    ports:
      - "3000:3000"
    user: "0:0"
